[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "hsmattest"
path = "./src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
hsmattest = { path = "../attest-verify-rs" }
